#include "Tiles.h"
#include "realm/Realm.h"

namespace Game3 {
	std::unordered_set<TileID> Monomap::landSet {
		SAND, LIGHT_GRASS, GRASS, GRASS_ALT1, GRASS_ALT2, ROAD, DIRT, TILES, STONE,
		CARPET1_NW, CARPET1_N, CARPET1_NE, CARPET1_W, CARPET1_C, CARPET1_E, CARPET1_SW, CARPET1_S, CARPET1_SE,
		CARPET2_NW, CARPET2_N, CARPET2_NE, CARPET2_W, CARPET2_C, CARPET2_E, CARPET2_SW, CARPET2_S, CARPET2_SE,
		CARPET3_NW, CARPET3_N, CARPET3_NE, CARPET3_W, CARPET3_C, CARPET3_E, CARPET3_SW, CARPET3_S, CARPET3_SE,
		FLOOR,
	};

	std::unordered_set<TileID> Monomap::solidSet {
		TOWER_NW, TOWER_NE, TOWER_SW, TOWER_SE, TOWER_WE, TOWER_NS, TOWER_N, TOWER_S, HOUSE1, HOUSE2, HOUSE3, MARKET1, MARKET2, MARKET3, KEEP_NW, KEEP_NE, KEEP_SW, KEEP_SE, IRON_ORE, DIAMOND_ORE,
		COPPER_ORE, GOLD_ORE, COAL_ORE, BLACKSMITH1, BLACKSMITH2, BLACKSMITH3, TREE1, TREE2, TREE3, IRON_ORE_REGEN, DIAMOND_ORE_REGEN, COPPER_ORE_REGEN, GOLD_ORE_REGEN, COAL_ORE_REGEN,
		WALL_NW, WALL_WE, WALL_NE, WALL_NS, WALL_SW, WALL_WE3, WALL_SE, WALL_E, WALL_W, BOOKSHELF, PLANT1, PLANT2, PLANT3, STOCKPILE_W, STOCKPILE_E, COUNTER, COUNTER_W, COUNTER_WE, COUNTER_E, ANVIL,
		FURNACE, WALL_N, WALL_WE2, WALL_NS2, WALL_NS3, WALL_S, WALL_NWES, WALL_NWS, WALL_NES, WALL_WES, WALL, WALL_NWE, DEEPER_WATER, DEEP_WATER, WATER,
	};

	std::unordered_set<TileID> Monomap::woodenWalls {
		WALL_NW, WALL_WE, WALL_NE, WALL_E, WALL_W, WALL_NS, WALL_SW, WALL_WE3, WALL_SE, WALL_N, WALL_WE2, WALL_NS2, WALL_NS3, WALL_S, WALL_NWES, WALL_NWS, WALL_NES, WALL_WES, WALL, WALL_NWE,
	};

	Monomap monomap;

	std::unordered_map<RealmID, std::shared_ptr<TileSet>> tileSets {
		{Realm::OVERWORLD,  std::make_shared<Monomap>()},
		{Realm::HOUSE,      std::make_shared<Monomap>()},
		{Realm::KEEP,       std::make_shared<Monomap>()},
		{Realm::BLACKSMITH, std::make_shared<Monomap>()},
	};
}
